------------------------
--Authorization tables--
------------------------

CREATE TABLE roles
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,

    CONSTRAINT pk_roles PRIMARY KEY (id),
    CONSTRAINT uk_roles_name UNIQUE (name)
);

CREATE INDEX idx_roles_name ON roles (name);

CREATE TABLE capabilities
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    description VARCHAR(255) NULL,

    CONSTRAINT pk_capabilities PRIMARY KEY (id),
    CONSTRAINT uk_capabilities_name UNIQUE (name)
);

CREATE INDEX idx_capabilities_name ON capabilities (name);

CREATE TABLE roles_capabilities
(
    role_id BIGINT NOT NULL,
    capability_id BIGINT NOT NULL,

    CONSTRAINT pk_roles_capabilities PRIMARY KEY (role_id, capability_id),
    CONSTRAINT fk_roles_capabilities_role_id FOREIGN KEY (role_id) REFERENCES roles(id)
        ON DELETE CASCADE,
    CONSTRAINT fk_roles_capabilities_capability_id FOREIGN KEY (capability_id) REFERENCES capabilities(id)
        ON DELETE CASCADE
);

CREATE INDEX idx_roles_capabilities_capability_id ON roles_capabilities (capability_id);

----------------------
--static data tables--
----------------------

CREATE TABLE regions
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,

    CONSTRAINT pk_regions PRIMARY KEY (id),
    CONSTRAINT uk_regions_name UNIQUE (name)
);

CREATE INDEX idx_regions_name ON regions (name);

CREATE TABLE professional_fields
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,

    CONSTRAINT pk_professional_fields PRIMARY KEY (id),
    CONSTRAINT uk_professional_fields_name UNIQUE (name)
);

CREATE INDEX idx_professional_fields_name ON professional_fields (name);

-----------------
--Domain tables--
-----------------

CREATE TABLE users
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,

    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uk_users_uuid UNIQUE (uuid),
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT fk_users_role_id FOREIGN KEY (role_id) REFERENCES roles (id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_users_username ON users (username);
CREATE INDEX idx_users_role_id ON users (role_id);
CREATE INDEX idx_users_deleted ON users (deleted);

CREATE TABLE personal_info
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    email VARCHAR(255) NOT NULL,
    telephone_number VARCHAR(10),
    address VARCHAR(255),
    region_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,

    CONSTRAINT pk_personal_info PRIMARY KEY (id),
    CONSTRAINT uk_personal_info_uuid UNIQUE (uuid),
    CONSTRAINT uk_personal_info_email UNIQUE (email),
    CONSTRAINT fk_personal_info_region_id FOREIGN KEY (region_id) REFERENCES regions (id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_personal_info_email ON personal_info (email);
CREATE INDEX idx_personal_info_region_id ON personal_info (region_id);

CREATE TABLE attachments
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    filename VARCHAR(255) NULL,
    saved_name VARCHAR(255) NOT NULL,
    filepath VARCHAR(1024) NOT NULL,
    content_type VARCHAR(255) NULL,
    extension VARCHAR(50) NULL,
    personal_info_id BIGINT NOT NULL,

    CONSTRAINT pk_attachments PRIMARY KEY (id),
    CONSTRAINT uk_attachments_uuid UNIQUE (uuid),
    CONSTRAINT uk_attachments_saved_name UNIQUE (saved_name),
    CONSTRAINT fk_attachments_personal_info_id FOREIGN KEY (personal_info_id) REFERENCES personal_info (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_attachments_saved_name ON attachments (saved_name);
CREATE INDEX idx_attachments_personal_info_id ON attachments (personal_info_id);

CREATE TABLE employers
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    brand_name VARCHAR(255) NOT NULL,
    vat VARCHAR(255) NOT NULL,
    website VARCHAR(255),
    user_id BIGINT NOT NULL,
    personal_info_id BIGINT NOT NULL,
    professional_field_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,

    CONSTRAINT pk_employers PRIMARY KEY (id),
    CONSTRAINT uk_employers_uuid UNIQUE (uuid),
    CONSTRAINT uk_employers_vat UNIQUE (vat),
    CONSTRAINT fk_employers_user FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_employers_personal_info FOREIGN KEY (personal_info_id) REFERENCES personal_info (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_employers_professional_field_id FOREIGN KEY (professional_field_id) REFERENCES professional_fields (id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_employers_brand_name ON employers (brand_name);
CREATE INDEX idx_employers_professional_field_id ON employers (professional_field_id);

CREATE TABLE job_seekers
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    user_id BIGINT NOT NULL,
    personal_info_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,

    CONSTRAINT pk_job_seekers PRIMARY KEY (id),
    CONSTRAINT uk_job_seekers_uuid UNIQUE (uuid),
    CONSTRAINT fk_job_seekers_user_id FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_job_seekers_personal_info_id FOREIGN KEY (personal_info_id) REFERENCES personal_info (id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_job_seekers_lastname ON job_seekers (lastname);

CREATE TABLE job_listings
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    professional_field_id BIGINT NOT NULL,
    employer_id BIGINT NOT NULL,
    region_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,

    CONSTRAINT pk_job_listings PRIMARY KEY (id),
    CONSTRAINT uk_job_listings_uuid UNIQUE (uuid),
    CONSTRAINT fk_job_listings_professional_field_id FOREIGN KEY (professional_field_id) REFERENCES professional_fields (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_job_listings_employer_id FOREIGN KEY (employer_id) REFERENCES employers (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_job_listings_region_id FOREIGN KEY (region_id) REFERENCES regions (id)
        ON DELETE RESTRICT
);

CREATE INDEX idx_job_listings_professional_field_id ON job_listings (professional_field_id);
CREATE INDEX idx_job_listings_employer_id ON job_listings (employer_id);
CREATE INDEX idx_job_listings_region_id ON job_listings (region_id);
CREATE INDEX idx_job_listings_deleted ON job_listings (deleted);

CREATE TABLE job_seekers_job_listings
(
    job_seeker_id BIGINT NOT NULL,
    job_listing_id BIGINT NOT NULL,

    CONSTRAINT pk_job_seekers_job_listings PRIMARY KEY (job_seeker_id, job_listing_id),
    CONSTRAINT fk_job_seekers_job_listings_job_seeker_id FOREIGN KEY (job_seeker_id) REFERENCES job_seekers (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_job_seekers_job_listings_job_listing_id FOREIGN KEY (job_listing_id) REFERENCES job_listings (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_job_seekers_job_listings_job_listing_id ON job_seekers_job_listings (job_listing_id);
CREATE INDEX idx_job_seekers_job_listings_job_seeker_id ON job_seekers_job_listings (job_seeker_id);

CREATE TABLE job_seeker_cvs
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    profession VARCHAR(255) NOT NULL,
    bio TEXT NULL,
    education TEXT NULL,
    experience TEXT NULL,
    certificates TEXT NULL,
    languages TEXT NULL,
    skills TEXT NULL,
    job_seeker_id BIGINT NOT NULL,

    CONSTRAINT pk_job_seeker_cvs PRIMARY KEY (id),
    CONSTRAINT fk_job_seeker_cvs_job_seeker_id FOREIGN KEY (job_seeker_id) REFERENCES job_seekers (id)
        ON DELETE CASCADE
);