CREATE TABLE applications
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    uuid UUID NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    job_seeker_id BIGINT NOT NULL,
    job_listing_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    deleted_at TIMESTAMPTZ NULL,

    CONSTRAINT pk_applications_id PRIMARY KEY (id),
    CONSTRAINT uk_applications_job_seeker_id_job_listing_id UNIQUE (job_seeker_id, job_listing_id),
    CONSTRAINT fk_applications_job_seeker_id FOREIGN KEY (job_seeker_id) REFERENCES job_seekers (id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_applications_job_listing_id FOREIGN KEY (job_listing_id) REFERENCES job_listings (id)
        ON DELETE RESTRICT
);